name: PR CI

on:
  pull_request:
    branches:
      - main
      - release/*

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  lint:
    name: Analyze
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ vars.FLUTTER_VERSION }}
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze
        shell: bash
        run: | 
          flutter analyze | tee ./flutter_analyze_report.txt

      - name: Setup ruby for Danger
        if: ${{ failure() }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version:  ${{ vars.DANGER_RUBY_VERSION }}
          bundler-cache: false

      - name: Setup danger
        if: ${{ failure() }}
        uses: MeilCli/danger-action@v5
        with:
          plugins_file: '.github/Gemfile'
          install_path: 'vendor/bundle'
          danger_file: '.github/Dangerfile'
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.TOKEN }}

