name: PR CI

on:
  pull_request:
    branches:
      - main
      - release/*

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ vars.FLUTTER_VERSION }}
          cache: true

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version:  ${{ vars.DANGER_RUBY_VERSION }}
          bundler-cache: true

      - name: Add matcher
        run: echo "::add-matcher::.github/problem-matcher-for-analyze.json"

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze
        shell: bash
        run: | 
          flutter analyze | tee ./flutter_analyze_report.txt

      - name: Remove matcher
        if: always()
        run: echo "::remove-matcher owner=flutter_lints::"

      - name: Comment analyze error
        uses: MeilCli/danger-action@v5
        if: always()
        with:
          plugins_file: '.github/Gemfile'
          install_path: 'vendor/bundle'
          danger_file: '.github/Dangerfile'
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.TOKEN }}

      - name: Test
        if: always()
        run: flutter test